name: CI-CD Pipeline
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t mydockerimage31/naresh-ci-cd-pipeline .

      - name: Push Docker Image
        run: docker push mydockerimage31/naresh-ci-cd-pipeline

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull mydockerimage31/naresh-ci-cd-pipeline
            docker stop naresh-container || true
            docker rm naresh-container || true
            docker run -d -p 8080:80 --name naresh-container mydockerimage31/naresh-ci-cd-pipeline
